// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnfD-CHNc3B-spL8aPG_eXQ_IZEdo_YOE',
    appId: '1:572870336776:web:7717aa1b60cb6143d98cbd',
    messagingSenderId: '572870336776',
    projectId: 'game-booster-randy',
    authDomain: 'game-booster-randy.firebaseapp.com',
    storageBucket: 'game-booster-randy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFcx6a5qZR2KyLbRuXBfSehVQYsWhDqWs',
    appId: '1:572870336776:android:2a5bca0e0ab24abfd98cbd',
    messagingSenderId: '572870336776',
    projectId: 'game-booster-randy',
    storageBucket: 'game-booster-randy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDebpFZ20zH_UvTpW02-QZSZ54eIkwGZc4',
    appId: '1:572870336776:ios:964b47a7bbf23cd8d98cbd',
    messagingSenderId: '572870336776',
    projectId: 'game-booster-randy',
    storageBucket: 'game-booster-randy.firebasestorage.app',
    iosBundleId: 'com.example.adminSensiBooster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDebpFZ20zH_UvTpW02-QZSZ54eIkwGZc4',
    appId: '1:572870336776:ios:964b47a7bbf23cd8d98cbd',
    messagingSenderId: '572870336776',
    projectId: 'game-booster-randy',
    storageBucket: 'game-booster-randy.firebasestorage.app',
    iosBundleId: 'com.example.adminSensiBooster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnfD-CHNc3B-spL8aPG_eXQ_IZEdo_YOE',
    appId: '1:572870336776:web:31a4d75639894649d98cbd',
    messagingSenderId: '572870336776',
    projectId: 'game-booster-randy',
    authDomain: 'game-booster-randy.firebaseapp.com',
    storageBucket: 'game-booster-randy.firebasestorage.app',
  );
}
